# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4f6112b606636924cd7fcf9bb4bee40a"
name = "baitosman"
handle = "baitosman"
application_url = "https://dump-criminal-tremendous-bother.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://dump-criminal-tremendous-bother.trycloudflare.com/auth/callback",
  "https://dump-criminal-tremendous-bother.trycloudflare.com/auth/shopify/callback",
  "https://dump-criminal-tremendous-bother.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
